# Generated by Django 5.0.7 on 2024-07-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=500)),
                ('objective', models.TextField(max_length=200)),
                ('motivation', models.TextField(max_length=500)),
                ('project_overview', models.TextField(max_length=1000)),
                ('methodology', models.TextField(max_length=2000)),
                ('discussion', models.TextField(max_length=1000)),
                ('conclusion', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('intial_line', models.CharField(max_length=50)),
                ('references', models.URLField()),
                ('project_links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libray_module_import', models.TextField(max_length=1000)),
                ('column_drop', models.TextField(max_length=1000)),
                ('preprocessing', models.TextField(max_length=1000)),
                ('stemming', models.TextField(max_length=1000)),
                ('report_methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodlogies', to='reportwriting1.report')),
            ],
        ),
    ]
