# Generated by Django 5.0.7 on 2024-07-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportwriting1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodology',
            options={'verbose_name': 'Methodology', 'verbose_name_plural': 'Methodologies'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Report'},
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='report_methodology',
        ),
        migrations.RemoveField(
            model_name='report',
            name='methodology',
        ),
        migrations.AddField(
            model_name='report',
            name='report_methodology',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='methodlogies', to='reportwriting1.methodology'),
        ),
    ]
